---
title: "Untitled"
output: html_document
date: "2023-12-12"
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r}
library(sf)
library(tidyverse)
library(lubridate)
library(sparta)
```

# Czech Atlases

## Atlas 2

```{r}
### CZ Atlas 2 #####
geopackage <- st_read("../data/frescalo_CZ.gpkg") %>%
  st_transform(., 5514)

## Create the ecological data
myData <-
  geopackage %>%
  select(cellID, verbatim_name, start_year) %>%
  filter(start_year == 1985) %>%
  mutate(tp = 1,
         time_period = years(1985)) %>%
  rename(site = cellID,taxa=verbatim_name,year = start_year) %>%
  st_drop_geometry()

## Create the period data
myTimePeriods <- data.frame(start = 1985, end = 1985)

## Get the euclidean distance between the grid cells
# First extract the coordinates
coords <-
  geopackage %>%
  filter(start_year == 1985) %>%
  distinct(cellID, .keep_all = T) %>%
  st_coordinates() %>%
  cbind(
    geopackage %>%
      st_drop_geometry() %>%
      filter(start_year == 1985) %>%
      distinct(cellID)
  )

## Create the distance matrix
dist <- as.matrix(dist(coords))
# dist[upper.tri(dist)] <- NA
## Transform into a df and names rows and cols
dist <-
  as.matrix(dist) %>%
  as.data.frame() %>%
  mutate(cellID = coords$cellID) %>%
  remove_rownames() %>%
  column_to_rownames("cellID")

colnames(dist) <- coords$cellID

## Transform into a long format
myDistances <-
  dist %>%
  rownames_to_column(var = "x") %>%
  pivot_longer(cols = -x,
               names_to = "y",
               values_to = "dist") %>%
  as.data.frame()

## Null habitat data
myHabitatData <-
  data.frame(site = coords$cellID, x = 1)

## Compute the weights
highWeights <- createWeights(distances = myDistances,
                             attributes = myHabitatData,
                             dist_sub = 200,
                             sim_sub = 100)
lowWeights <- createWeights(distances = myDistances,
                             attributes = myHabitatData,
                             dist_sub = 20,
                             sim_sub = 10)


## Run Frescalo
frescalo_results_highWeights <- frescalo(Data = myData,
                             frespath = paste0(getwd(),"/../Frescalo_3a_windows.exe"),
                             time_periods = myTimePeriods,
                             site_col = "site",
                             sp_col = "taxa",
                             year = "year",
                             Fres_weights = highWeights,
                             sinkdir = paste0(getwd(),"/../output/"),
                             phi = NULL)
frescalo_results_lowWeights <- frescalo(Data = myData,
                                         frespath = paste0(getwd(),"/../Frescalo_3a_windows.exe"),
                                         time_periods = myTimePeriods,
                                         site_col = "site",
                                         sp_col = "taxa",
                                         year = "year",
                                         Fres_weights = lowWeights,
                                         sinkdir = paste0(getwd(),"/../output/"),
                                         phi = NULL)

## Get data from atlas 2
atlas2 <- geopackage %>% filter(start_year == 1985)

## Get sampling effort for atlas 2
effort_atlas <- atlas2 %>%
  select(cellID, effort) %>%
  filter(effort != 0) %>%
  rename(atlasCards = effort) %>%
  distinct()

## Compute effort from frescalo output
frescalo_results_highWeights$stat$effortFresc <- 1/frescalo_results_highWeights$stat$Alpha
frescalo_results_lowWeights$stat$effortFresc <- 1/frescalo_results_lowWeights$stat$Alpha

sr_atlas2 <-
  atlas2 %>% st_drop_geometry() %>%  group_by(cellID) %>% summarise(sr = length(unique(verbatim_name)))

corD <-
  sr_atlas2 %>%
  left_join(effort_atlas) %>%
  left_join(
    rbind(frescalo_results_highWeights$stat %>% select(Location, effortFresc) %>% rename(cellID = Location) %>% mutate(weights = "high"),
          frescalo_results_lowWeights$stat %>% select(Location, effortFresc) %>% rename(cellID = Location) %>% mutate(weights = "low"))
  ) %>%
  mutate(atlas = "CZ_atlas2")
```

## Atlas 3

```{r}
## Create the ecological data
myData <-
  geopackage %>%
  select(cellID, verbatim_name, start_year) %>%
  filter(start_year == 2001) %>%
  mutate(tp = 1,
         time_period = years(2001)) %>%
  rename(site = cellID,taxa=verbatim_name,year = start_year) %>%
  st_drop_geometry()

## Create the period data
myTimePeriods <- data.frame(start = 2001, end = 2001)

## Get the euclidean distance between the grid cells
# First extract the coordinates
coords <-
  geopackage %>%
  filter(start_year == 2001) %>%
  distinct(cellID, .keep_all = T) %>%
  st_coordinates() %>%
  cbind(
    geopackage %>%
      st_drop_geometry() %>%
      filter(start_year == 2001) %>%
      distinct(cellID)
  )

## Create the distance matrix
dist <- as.matrix(dist(coords))
# dist[upper.tri(dist)] <- NA
## Transform into a df and names rows and cols
dist <-
  as.matrix(dist) %>%
  as.data.frame() %>%
  mutate(cellID = coords$cellID) %>%
  remove_rownames() %>%
  column_to_rownames("cellID")

colnames(dist) <- coords$cellID

## Transform into a long format
myDistances <-
  dist %>%
  rownames_to_column(var = "x") %>%
  pivot_longer(cols = -x,
               names_to = "y",
               values_to = "dist") %>%
  as.data.frame()

## Null habitat data
myHabitatData <-
  data.frame(site = coords$cellID, x = 1)

## Compute the weights
lowWeights <- createWeights(distances = myDistances,
                           attributes = myHabitatData,
                           dist_sub = 20,
                           sim_sub = 10)
highWeights <- createWeights(distances = myDistances,
                            attributes = myHabitatData,
                            dist_sub = 200,
                            sim_sub = 100)


## Run Frescalo
frescalo_results_highWeights <- frescalo(Data = myData,
                             frespath = paste0(getwd(),"/../Frescalo_3a_windows.exe"),
                             time_periods = myTimePeriods,
                             site_col = "site",
                             sp_col = "taxa",
                             year = "year",
                             Fres_weights = highWeights,
                             sinkdir = paste0(getwd(),"/../output/"),
                             phi = NULL)
frescalo_results_lowWeights <- frescalo(Data = myData,
                                         frespath = paste0(getwd(),"/../Frescalo_3a_windows.exe"),
                                         time_periods = myTimePeriods,
                                         site_col = "site",
                                         sp_col = "taxa",
                                         year = "year",
                                         Fres_weights = lowWeights,
                                         sinkdir = paste0(getwd(),"/../output/"),
                                         phi = NULL)

## Get data from atlas 3
atlas3 <- geopackage %>% filter(start_year == 2001)

## Get sampling effort for atlas 3
effort_atlas <- atlas3 %>%
  select(cellID, effort) %>%
  filter(effort != 0) %>%
  rename(atlasCards = effort) %>%
  distinct()

## Compute effort from frescalo output
frescalo_results_highWeights$stat$effortFresc <- 1/frescalo_results_highWeights$stat$Alpha
frescalo_results_lowWeights$stat$effortFresc <- 1/frescalo_results_lowWeights$stat$Alpha

sr_atlas3 <-
  atlas3 %>% st_drop_geometry() %>%  group_by(cellID) %>% summarise(sr = length(unique(verbatim_name)))

corD <-
  rbind(corD,
        sr_atlas3 %>%
          left_join(effort_atlas) %>%
          left_join(
            rbind(frescalo_results_highWeights$stat %>% select(Location, effortFresc) %>% rename(cellID = Location) %>% mutate(weights = "high"),
                  frescalo_results_lowWeights$stat %>% select(Location, effortFresc) %>% rename(cellID = Location) %>% mutate(weights = "low"))
          ) %>%
          mutate(atlas = "CZ_atlas3")
  )

```

## Atlas 4

```{r}
## Create the ecological data
myData <-
  geopackage %>%
  select(cellID, verbatim_name, start_year) %>%
  filter(start_year == 2014) %>%
  mutate(tp = 1,
         time_period = years(2014)) %>%
  rename(site = cellID,taxa=verbatim_name,year = start_year) %>%
  st_drop_geometry()

## Create the period data
myTimePeriods <- data.frame(start = 2014, end = 2014)

## Get the euclidean distance between the grid cells
# First extract the coordinates
coords <-
  geopackage %>%
  filter(start_year == 2014) %>%
  distinct(cellID, .keep_all = T) %>%
  st_coordinates() %>%
  cbind(
    geopackage %>%
      st_drop_geometry() %>%
      filter(start_year == 2014) %>%
      distinct(cellID)
  )

## Create the distance matrix
dist <- as.matrix(dist(coords))
# dist[upper.tri(dist)] <- NA
## Transform into a df and names rows and cols
dist <-
  as.matrix(dist) %>%
  as.data.frame() %>%
  mutate(cellID = coords$cellID) %>%
  remove_rownames() %>%
  column_to_rownames("cellID")

colnames(dist) <- coords$cellID

## Transform into a long format
myDistances <-
  dist %>%
  rownames_to_column(var = "x") %>%
  pivot_longer(cols = -x,
               names_to = "y",
               values_to = "dist") %>%
  as.data.frame()

## Null habitat data
myHabitatData <-
  data.frame(site = coords$cellID, x = 1)

## Compute the weights
highWeights <- createWeights(distances = myDistances,
                           attributes = myHabitatData,
                           dist_sub = 200,
                           sim_sub = 100)
lowWeights <- createWeights(distances = myDistances,
                             attributes = myHabitatData,
                             dist_sub = 20,
                             sim_sub = 10)


## Run Frescalo
frescalo_results_lowWeights <- frescalo(Data = myData,
                             frespath = paste0(getwd(),"/../Frescalo_3a_windows.exe"),
                             time_periods = myTimePeriods,
                             site_col = "site",
                             sp_col = "taxa",
                             year = "year",
                             Fres_weights = lowWeights,
                             sinkdir = paste0(getwd(),"/../output/"),
                             phi = NULL)
frescalo_results_highWeights <- frescalo(Data = myData,
                                        frespath = paste0(getwd(),"/../Frescalo_3a_windows.exe"),
                                        time_periods = myTimePeriods,
                                        site_col = "site",
                                        sp_col = "taxa",
                                        year = "year",
                                        Fres_weights = highWeights,
                                        sinkdir = paste0(getwd(),"/../output/"),
                                        phi = NULL)

## Get data from atlas 4
atlas4 <- geopackage %>% filter(start_year == 2014)

## Get sampling effort for atlas 4
effort_atlas <- atlas4 %>%
  select(cellID, effort) %>%
  filter(effort != 0) %>%
  rename(observers = effort) %>%
  distinct()

## Compute effort from frescalo output
frescalo_results_highWeights$stat$effortFresc <- 1/frescalo_results_highWeights$stat$Alpha
frescalo_results_lowWeights$stat$effortFresc <- 1/frescalo_results_lowWeights$stat$Alpha

sr_atlas4 <-
  atlas4 %>% st_drop_geometry() %>%  group_by(cellID) %>% summarise(sr = length(unique(verbatim_name)))

corD <-
  bind_rows(corD,
        sr_atlas4 %>%
          left_join(effort_atlas) %>%
          left_join(
            rbind(frescalo_results_highWeights$stat %>% select(Location, effortFresc) %>% rename(cellID = Location) %>% mutate(weights = "high"),
                  frescalo_results_lowWeights$stat %>% select(Location, effortFresc) %>% rename(cellID = Location) %>% mutate(weights = "low"))
          ) %>%
          mutate(atlas = "CZ_atlas4")
  )
```
# New York state Atlases

## Atlas 1

```{r}
geopackage <- st_read("../data/frescalo_NY.gpkg") %>%
  st_transform(., 4326)

geopackage <- geopackage %>% st_cast(to = "POINT", group_or_split = FALSE, do_split = FALSE)

## Create the ecological data
myData <-
  geopackage %>%
  select(cellID, verbatim_name, start_year) %>%
  filter(start_year == 1980) %>%
  mutate(tp = 1,
         time_period = years(1980)) %>%
  rename(site = cellID,taxa=verbatim_name,year = start_year) %>%
  st_drop_geometry()

## Create the period data
myTimePeriods <- data.frame(start = 1980, end = 1980)

## Get the euclidean distance between the grid cells
# First extract the coordinates
coords <-
  geopackage %>%
  filter(start_year == 1980) %>%
  distinct(cellID, .keep_all = T) %>%
  st_coordinates() %>%
  cbind(
    geopackage %>%
      st_drop_geometry() %>%
      filter(start_year == 1980) %>%
      distinct(cellID)
  )

## Create the distance matrix
dist <- as.matrix(dist(coords))
# dist[upper.tri(dist)] <- NA
## Transform into a df and names rows and cols
dist <-
  as.matrix(dist) %>%
  as.data.frame() %>%
  mutate(cellID = coords$cellID) %>%
  remove_rownames() %>%
  column_to_rownames("cellID")

colnames(dist) <- coords$cellID

## Transform into a long format
myDistances <-
  dist %>%
  rownames_to_column(var = "x") %>%
  pivot_longer(cols = -x,
               names_to = "y",
               values_to = "dist") %>%
  as.data.frame()

## Null habitat data
myHabitatData <-
  data.frame(site = coords$cellID, x = 1)

## Compute the weights
highWeights <- createWeights(distances = myDistances,
                             attributes = myHabitatData,
                             dist_sub = 200,
                             sim_sub = 100)
lowWeights <- createWeights(distances = myDistances,
                            attributes = myHabitatData,
                            dist_sub = 20,
                            sim_sub = 10)


## Run Frescalo
frescalo_results_highWeights <- frescalo(Data = myData,
                                         frespath = paste0(getwd(),"/../Frescalo_3a_windows.exe"),
                                         time_periods = myTimePeriods,
                                         site_col = "site",
                                         sp_col = "taxa",
                                         year = "year",
                                         Fres_weights = highWeights,
                                         sinkdir = paste0(getwd(),"/../output/"),
                                         phi = NULL)
frescalo_results_lowWeights <- frescalo(Data = myData,
                                        frespath = paste0(getwd(),"/../Frescalo_3a_windows.exe"),
                                        time_periods = myTimePeriods,
                                        site_col = "site",
                                        sp_col = "taxa",
                                        year = "year",
                                        Fres_weights = lowWeights,
                                        sinkdir = paste0(getwd(),"/../output/"),
                                        phi = NULL)


## Get data from atlas 2
NY_atlas1 <- geopackage %>% filter(start_year == 1980)

## Get sampling effort for atlas 4
effort_atlas <- NY_atlas1 %>%
  select(cellID, effort) %>%
  filter(effort != 0) %>%
  rename(hours = effort) %>%
  distinct()

## Compute effort from frescalo output
frescalo_results_highWeights$stat$effortFresc <- 1/frescalo_results_highWeights$stat$Alpha
frescalo_results_lowWeights$stat$effortFresc <- 1/frescalo_results_lowWeights$stat$Alpha

sr_NYatlas1 <-
  NY_atlas1 %>% st_drop_geometry() %>%  group_by(cellID) %>% summarise(sr = length(unique(verbatim_name)))

corD <-
  bind_rows(corD %>% mutate(cellID = as.character(cellID)),
            sr_NYatlas1 %>%
              left_join(effort_atlas) %>%
              left_join(
                rbind(frescalo_results_highWeights$stat %>% select(Location, effortFresc) %>% rename(cellID = Location) %>% mutate(weights = "high"),
                      frescalo_results_lowWeights$stat %>% select(Location, effortFresc) %>% rename(cellID = Location) %>% mutate(weights = "low"))
              ) %>%
              mutate(atlas = "NY_atlas1")
  )
```

## Atlas 2

```{r}
## Create the ecological data
myData <-
  geopackage %>%
  select(cellID, verbatim_name, start_year) %>%
  filter(start_year == 2000) %>%
  mutate(tp = 1,
         time_period = years(2000)) %>%
  rename(site = cellID,taxa=verbatim_name,year = start_year) %>%
  st_drop_geometry()

## Create the period data
myTimePeriods <- data.frame(start = 2000, end = 2000)

## Get the euclidean distance between the grid cells
# First extract the coordinates
coords <-
  geopackage %>%
  filter(start_year == 2000) %>%
  distinct(cellID, .keep_all = T) %>%
  st_coordinates() %>%
  cbind(
    geopackage %>%
      st_drop_geometry() %>%
      filter(start_year == 2000) %>%
      distinct(cellID)
  )

## Create the distance matrix
dist <- as.matrix(dist(coords))
# dist[upper.tri(dist)] <- NA
## Transform into a df and names rows and cols
dist <-
  as.matrix(dist) %>%
  as.data.frame() %>%
  mutate(cellID = coords$cellID) %>%
  remove_rownames() %>%
  column_to_rownames("cellID")

colnames(dist) <- coords$cellID

## Transform into a long format
myDistances <-
  dist %>%
  rownames_to_column(var = "x") %>%
  pivot_longer(cols = -x,
               names_to = "y",
               values_to = "dist") %>%
  as.data.frame()

## Null habitat data
myHabitatData <-
  data.frame(site = coords$cellID, x = 1)

## Compute the weights
highWeights <- createWeights(distances = myDistances,
                             attributes = myHabitatData,
                             dist_sub = 200,
                             sim_sub = 100)
lowWeights <- createWeights(distances = myDistances,
                            attributes = myHabitatData,
                            dist_sub = 20,
                            sim_sub = 10)


## Run Frescalo
frescalo_results_highWeights <- frescalo(Data = myData,
                                         frespath = paste0(getwd(),"/../Frescalo_3a_windows.exe"),
                                         time_periods = myTimePeriods,
                                         site_col = "site",
                                         sp_col = "taxa",
                                         year = "year",
                                         Fres_weights = highWeights,
                                         sinkdir = paste0(getwd(),"/../output/"),
                                         phi = NULL)
frescalo_results_lowWeights <- frescalo(Data = myData,
                                        frespath = paste0(getwd(),"/../Frescalo_3a_windows.exe"),
                                        time_periods = myTimePeriods,
                                        site_col = "site",
                                        sp_col = "taxa",
                                        year = "year",
                                        Fres_weights = lowWeights,
                                        sinkdir = paste0(getwd(),"/../output/"),
                                        phi = NULL)


## Get data from atlas 2
NY_atlas2 <- geopackage %>% filter(start_year == 2000)

## Get sampling effort for atlas 4
effort_atlas <- NY_atlas2 %>%
  select(cellID, effort) %>%
  filter(effort != 0) %>%
  rename(hours = effort) %>%
  distinct()

## Compute effort from frescalo output
frescalo_results_highWeights$stat$effortFresc <- 1/frescalo_results_highWeights$stat$Alpha
frescalo_results_lowWeights$stat$effortFresc <- 1/frescalo_results_lowWeights$stat$Alpha

sr_NYatlas2 <-
  NY_atlas2 %>% st_drop_geometry() %>%  group_by(cellID) %>% summarise(sr = length(unique(verbatim_name)))

corD <-
  bind_rows(corD %>% mutate(cellID = as.character(cellID)),
            sr_NYatlas1 %>%
              left_join(effort_atlas) %>%
              left_join(
                rbind(frescalo_results_highWeights$stat %>% select(Location, effortFresc) %>% rename(cellID = Location) %>% mutate(weights = "high"),
                      frescalo_results_lowWeights$stat %>% select(Location, effortFresc) %>% rename(cellID = Location) %>% mutate(weights = "low"))
              ) %>%
              mutate(atlas = "NY_atlas2")
  )
```


# Correlation plot

```{r}
### Correlation plot #####
library(recipes)
library(ggforce)

tmp <-
  corD %>%
  pivot_wider(names_from = weights,
              values_from = effortFresc,
              names_prefix = "frescalo_weights_") %>%
  select(-cellID, -geom)

# pdf("figures/corplot.pdf" ,
#     width = 8.27, height = 5.83)

ggplot(tmp, aes(x = .panel_x, y = .panel_y, fill = atlas, colour = atlas)) +
  geom_point(alpha = .5, shape = 16, size = 1, position = 'auto') +
  geom_autodensity(alpha = .5, position = 'identity') +
  facet_matrix(vars(-atlas),
               layer.diag = 2,
               grid.y.diag = F)+
  theme_bw()

# dev.off()

```

